CREATE TABLE CUSTOMERS
(
    ID              NUMBER(19)    NOT NULL,
    FIRST_NAME      VARCHAR2(100) NOT NULL,
    LAST_NAME       VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(255) NOT NULL,
    PHONE           VARCHAR2(20),
    STATUS          VARCHAR2(20)  NOT NULL,
    CUSTOMER_REF_NO VARCHAR2(20),
    CREATED_AT      TIMESTAMP     NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
)